// frontend/src/components/LoginPanel.tsx
import { LogIn } from 'lucide-react';
import { FormEvent, useState } from 'react';

interface LoginPanelProps {
  isLoading: boolean;
  errorMessage: string | null;
  onSubmit: (credentials: { studentIdentity: string; password: string; rememberMe: boolean }) => Promise<void>;
}

export function LoginPanel({ isLoading, errorMessage, onSubmit }: LoginPanelProps) {
  const [studentIdentity, setStudentIdentity] = useState('');
  const [password, setPassword] = useState('');
  const [rememberMe, setRememberMe] = useState(false);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    await onSubmit({ studentIdentity, password, rememberMe });
  }

  return (
    <section className="login-panel" aria-labelledby="login-title">
      <div>
        <h2 id="login-title">队员登录</h2>
        <p>welcome to custacmwiki</p>
      </div>
      <form onSubmit={handleSubmit}>
        <label>
          学号姓名
          <input
            autoComplete="username"
            onChange={(event) => setStudentIdentity(event.target.value)}
            placeholder="输入学号姓名"
            required
            value={studentIdentity}
          />
        </label>
        <label>
          密码
          <input
            autoComplete="current-password"
            onChange={(event) => setPassword(event.target.value)}
            placeholder="输入密码"
            required
            type="password"
            value={password}
          />
        </label>
        <label className="checkbox-field login-remember-field">
          <span>记住我一个月</span>
          <input
            checked={rememberMe}
            onChange={(event) => setRememberMe(event.target.checked)}
            type="checkbox"
          />
        </label>
        <button className="primary-button" disabled={isLoading} type="submit">
          <LogIn size={16} aria-hidden="true" />
          {isLoading ? '登录中' : '登录'}
        </button>
      </form>
      {errorMessage ? <p className="form-error" role="alert">{errorMessage}</p> : null}
    </section>
  );
}

// frontend/src/components/LoginPanel.vue
<template>
  <section class="login-page" aria-labelledby="login-title">
    <div class="login-card">
      <header>
        <span class="login-eyebrow">TRAINING CENTER</span>
        <h1 id="login-title">登录训练中心</h1>
        <p>使用 custacm wiki 账号继续访问训练数据。</p>
      </header>
      <form @submit.prevent="submit">
        <label>用户名<input v-model="username" autocomplete="username" placeholder="输入用户名" required /></label>
        <label>密码<input v-model="password" autocomplete="current-password" placeholder="输入密码" required type="password" /></label>
        <button class="primary-button login-submit" :disabled="loading" type="submit">
          <LogIn :size="16" aria-hidden="true" />{{ loading ? '登录中' : '登录' }}
        </button>
      </form>
      <p v-if="errorMessage" class="form-error" role="alert">{{ errorMessage }}</p>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { LogIn } from '@lucide/vue';

// Author: huangbingrui.awa
const props = defineProps<{ signIn(username: string, password: string): Promise<void> }>();
const username = ref('');
const password = ref('');
const loading = ref(false);
const errorMessage = ref('');
async function submit() {
  loading.value = true;
  errorMessage.value = '';
  try {
    await props.signIn(username.value, password.value);
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : '登录失败。';
    password.value = '';
  } finally {
    loading.value = false;
  }
}
</script>
